<?php


namespace VRobin\Weixin3rd\Request\Apis;


use VRobin\Weixin3rd\Request\Request;

class ApiGetAuthorizerList extends Request
{
    protected $api = 'component/api_get_authorizer_list';
    protected $method = 'POST';
    protected $needAppid = true;

    public function setOffset($value){
        $this->data['offset'] = $value;
    }

    public function setCount($value){
        $this->data['count'] = $value;
    }

    public function getData()
    {
        if(!isset($this->data['offset'])){
            $this->data['offset'] = 0;
        }
        if(!isset($this->data['count'])){
            $this->data['count'] = 100;
        }
        return parent::getData(); // TODO: Change the autogenerated stub
    }
}